branch-defaults:
  master:
    environment: snt-api-prod
    group_suffix: null
  pre:
    environment: snt-api-pre
    group_suffix: null
  dev:
    environment: snt-api-dev
    group_suffix: null
environment-defaults:
  snt-api-prod:
    branch: master
    repository: null
  snt-api-pre:
    branch: pre
    repository: null
  snt-api-dev:
    branch: dev
    repository: null
global:
  application_name: snt-api
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
