version: 2

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - build_dev:
          filters:
            branches:
              only: dev
      - build_prod:
          filters:
            branches:
              only:
                - pre
                - master
      - deploy-dev:
          requires:
            - build_dev
          filters:
            branches:
              only: dev
      - deploy-pre:
          requires:
            - build_prod
          filters:
            branches:
              only: pre
      - deploy-prod:
          requires:
            - build_prod
          filters:
            branches:
              only: master

jobs:
  build_dev:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers

    environment:
      - CC_TEST_REPORTER_ID: 6d2db401af9828e9c7fd68b099683c91d21caf7b160580f226e8f6c91358bf60
      - DJANGO_SETTINGS_MODULE: sentad.settings.dev
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements/dev.txt
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          paths:
            - ./venv
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test
      - run:
          name: Generate coverage
          command: |
            . venv/bin/activate
            python -m coverage run --source='.' manage.py test
            python -m coverage xml
            ./cc-test-reporter after-build < coverage.xml

  build_prod:
    environment:
      - CC_TEST_REPORTER_ID: 6d2db401af9828e9c7fd68b099683c91d21caf7b160580f226e8f6c91358bf60
      - DJANGO_SETTINGS_MODULE: sentad.settings.prod
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          paths:
            - ./venv
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test
      - run:
          name: Generate coverage
          command: |
            . venv/bin/activate
            python -m coverage run --source='.' manage.py test
            python -m coverage xml
            ./cc-test-reporter after-build < coverage.xml

  deploy-dev:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install elasticbeanstalk CLI
          command: |
            mkdir ~/.aws
            echo -e "[eb-cli]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials
            python3 -m venv venv
            . venv/bin/activate
            pip install awsebcli
      - run:
          name: Deploy to elasticbeanstalk DEV
          command: |
            . venv/bin/activate
            eb deploy snt-api-dev

  deploy-pre:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install elasticbeanstalk CLI
          command: |
            mkdir ~/.aws
            echo -e "[eb-cli]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials
            python3 -m venv venv
            . venv/bin/activate
            pip install awsebcli
      - run:
          name: Deploy to elasticbeanstalk PRE
          command: |
            . venv/bin/activate
            eb deploy snt-api-pre


  deploy-prod:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install elasticbeanstalk CLI
          command: |
            mkdir ~/.aws
            echo -e "[eb-cli]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials
            python3 -m venv venv
            . venv/bin/activate
            pip install awsebcli
      - run:
          name: Deploy to elasticbeanstalk PROD
          command: |
            . venv/bin/activate
            eb deploy snt-api-prod