version: 2

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy-pre:
          requires:
            - build
          filters:
            branches:
              only: pre
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 6d2db401af9828e9c7fd68b099683c91d21caf7b160580f226e8f6c91358bf60
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          paths:
            - ./venv
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test
      - run:
          name: Generate coverage
          command: |
            . venv/bin/activate
            python -m coverage run --source='.' manage.py test
            python -m coverage xml
            ./cc-test-reporter after-build < coverage.xml

  deploy-dev:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install elasticbeanstalk CLI
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install awsebcli
      - run:
          name: Deploy to elasticbeanstalk dev
          command: |
            mkdir ~/.aws
            echo -e "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID_PROD\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY_PROD\n" > ~/.aws/credentials
            . venv/bin/activate
            eb init --profile default -r us-east-1 -k default
            eb deploy snt-api-dev

  deploy-pre:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install elasticbeanstalk CLI
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install awsebcli
      - run:
          name: Deploy to elasticbeanstalk pre
          command: |
            . venv/bin/activate
            eb deploy snt-api-pre


  deploy-prod:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install elasticbeanstalk CLI
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install awsebcli
      - run:
          name: Deploy to elasticbeanstalk prod
          command: |
            . venv/bin/activate
            eb deploy snt-api-prod
